---
# tasks file for istioctl | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and extracting {{ istioctl_app }} {{ istioctl_version }}
  ansible.builtin.unarchive:
    src: "{{ istioctl_dl_url }}"
    dest: "{{ istioctl_bin_path }}"
    extra_opts:
      - --strip-components=2
      - "istio-{{ istioctl_version }}/bin/{{ istioctl_app }}"
    remote_src: yes
    owner: "{{ istioctl_file_owner }}"
    group: "{{ istioctl_file_group }}"
    mode: "{{ istioctl_file_mode }}"
